name: fwo_admin
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.0+1
  geolocator: ^12.0.0
  flutter_phone_direct_caller: ^2.1.1
  direct_caller_sim_choice: ^1.0.5
  maps_launcher: ^2.2.1
  map_launcher: ^3.3.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator:
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
